# Generated by Django 3.1.7 on 2021-03-12 22:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=333)),
                ('won', models.BooleanField(default=False)),
                ('date_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=50)),
                ('goofy', models.BooleanField(default=False)),
                ('fav_skater', models.CharField(max_length=50)),
                ('fav_video', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('stance', models.IntegerField()),
                ('description', models.CharField(max_length=333)),
                ('skater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skatebetterapi.skater')),
            ],
        ),
        migrations.CreateModel(
            name='Opponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=50)),
                ('goofy', models.BooleanField(default=False)),
                ('skater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skatebetterapi.skater')),
            ],
        ),
        migrations.CreateModel(
            name='GameTrick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skatebetterapi.game')),
                ('trick', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='skatebetterapi.trick')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='opponent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skatebetterapi.opponent'),
        ),
        migrations.AddField(
            model_name='game',
            name='skater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skatebetterapi.skater'),
        ),
    ]
