# Generated by Django 3.1.7 on 2021-03-18 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skatebetterapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gametrick',
            name='opponent_make',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gametrick',
            name='user_make',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='skater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skaters', to='skatebetterapi.skater'),
        ),
    ]
